# Generated by Django 5.1.3 on 2024-11-27 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('votos', models.IntegerField(default=0)),
                ('geolocalizacao', models.CharField(blank=True, null=True)),
                ('natureza', models.CharField(choices=[('1', 'denúncias'), ('2', 'dúvidas'), ('3', 'elogios'), ('4', 'reclamações'), ('5', 'serviços'), ('6', 'sugestões'), ('7', 'urgências')])),
                ('status', models.CharField(choices=[('1', 'pendente'), ('2', 'resolvido'), ('3', 'falso')], default='1')),
                ('anonima', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
