# Generated by Django 5.1.3 on 2024-12-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='natureza',
            field=models.CharField(choices=[('1', 'infraestrutura'), ('2', 'iluminação'), ('3', 'coleta de lixo'), ('4', 'saneamento'), ('5', 'trânsito'), ('6', 'outro')], max_length=1),
        ),
    ]
