# Generated by Django 5.1.3 on 2025-01-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_postagem_votos_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Feminino'), ('n', 'Não informado')], max_length=1, null=True),
        ),
    ]
