# Generated by Django 5.1.3 on 2025-01-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(blank=True, choices=[('cidadão', 'Cidadão'), ('ouvidoria', 'Ouvidoria')], max_length=9, null=True),
        ),
    ]
