# Generated by Django 5.1.3 on 2025-01-29 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cpf', message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')]),
        ),
    ]
