# Generated by Django 5.1.3 on 2025-01-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='path_pdf',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
