# Generated by Django 5.1.3 on 2025-02-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_postagem_path_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='quantidade_reclamacoes',
            field=models.IntegerField(default=0),
        ),
    ]
